//Preset colors
#define CLR_BLACK__     0x0000
#define CLR_RED____     0x001F
#define CLR_LIME___     0x03E0
#define CLR_YELLOW_     0x03FF
#define CLR_BLUE___     0x7C00
#define CLR_MAG____     0x7C1F
#define CLR_CYAN___     0x7FE0
#define CLR_WHITE__		0x7FFF

//My colors
#define CLR_PURPLE_ 	0xF88F
#define CLR_MY_CYAN		0xF180
#define CLR_MY_RED_ 	0x18D7
#define CLR_BROWN__ 	0x194F
#define CLR_GREY___ 	0x20E4
#define CLR_L_GREY_ 	0x734D
#define CLR_DARK_GR		0x0A01

//transparent
#define CLR_TRANSP_ 	0000-1

int player_up[8][8] = {
			{CLR_TRANSP_, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_GREY___, CLR_GREY___, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_GREY___, CLR_GREY___},
			{CLR_GREY___, CLR_L_GREY_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_L_GREY_, CLR_GREY___},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_GREY___, CLR_GREY___, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_GREY___, CLR_GREY___},
			{CLR_GREY___, CLR_L_GREY_, CLR_BROWN__, CLR_MY_RED_, CLR_MY_RED_, CLR_BROWN__, CLR_L_GREY_, CLR_GREY___},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_BROWN__, CLR_TRANSP_, CLR_TRANSP_, CLR_BROWN__, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_TRANSP_}
				   };
int player_down[8][8] = {
			{CLR_TRANSP_, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_BROWN__, CLR_TRANSP_, CLR_TRANSP_, CLR_BROWN__, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_GREY___, CLR_L_GREY_, CLR_BROWN__, CLR_MY_RED_, CLR_MY_RED_, CLR_BROWN__, CLR_L_GREY_, CLR_GREY___},
			{CLR_GREY___, CLR_GREY___, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_GREY___, CLR_GREY___},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_GREY___, CLR_L_GREY_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_L_GREY_, CLR_GREY___},
			{CLR_GREY___, CLR_GREY___, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_GREY___, CLR_GREY___},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_TRANSP_},
				   };
int player_left[8][8] = {
			{CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_GREY___, CLR_L_GREY_, CLR_TRANSP_, CLR_GREY___, CLR_L_GREY_, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_BROWN__, CLR_BROWN__, CLR_GREY___},
			{CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_GREY___},
			{CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_TRANSP_, CLR_GREY___},
			{CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_BROWN__, CLR_BROWN__, CLR_GREY___},
			{CLR_TRANSP_, CLR_GREY___, CLR_L_GREY_, CLR_TRANSP_, CLR_GREY___, CLR_L_GREY_, CLR_TRANSP_, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_TRANSP_}
				   };
int player_right[8][8] = {
			{CLR_TRANSP_, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_L_GREY_, CLR_GREY___, CLR_TRANSP_, CLR_L_GREY_, CLR_GREY___, CLR_TRANSP_},
			{CLR_GREY___, CLR_BROWN__, CLR_BROWN__, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_},
			{CLR_GREY___, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_},
			{CLR_GREY___, CLR_TRANSP_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_},
			{CLR_GREY___, CLR_BROWN__, CLR_BROWN__, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_, CLR_MY_RED_},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_L_GREY_, CLR_GREY___, CLR_TRANSP_, CLR_L_GREY_, CLR_GREY___, CLR_TRANSP_},
			{CLR_TRANSP_, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_, CLR_GREY___, CLR_GREY___, CLR_TRANSP_}
				   };
				   
int grass[8][8] = {
		{CLR_DARK_GR, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_, CLR_DARK_GR},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_DARK_GR, CLR_TRANSP_}
};

int clear_grass[8][8] = {
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_},
		{CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_, CLR_TRANSP_}
};

bool letter[10][25] = {
	{
		0,1,1,1,0,
		0,1,0,1,0,
		0,1,0,1,0,
		0,1,0,1,0,
		0,1,1,1,0
	},
	{
		0,0,1,0,0,
		0,1,1,0,0,
		0,0,1,0,0,
		0,0,1,0,0,
		0,1,1,1,0
	},
	{
		0,1,1,1,0,
		0,0,0,1,0,
		0,1,1,1,0,
		0,1,0,0,0,
		0,1,1,1,0
	},
	{
		0,1,1,1,0,
		0,0,0,1,0,
		0,1,1,1,0,
		0,0,0,1,0,
		0,1,1,1,0
	},
	{
		0,1,0,1,0,
		0,1,0,1,0,
		0,1,1,1,0,
		0,0,0,1,0,
		0,0,0,1,0
	},
	{
		0,1,1,1,0,
		0,1,0,0,0,
		0,1,1,1,0,
		0,0,0,1,0,
		0,1,1,1,0
	},
	{
		0,1,1,1,0,
		0,1,0,0,0,
		0,1,1,1,0,
		0,1,0,1,0,
		0,1,1,1,0
	},
	{
		0,1,1,1,0,
		0,0,0,1,0,
		0,0,1,0,0,
		0,0,1,0,0,
		0,0,1,0,0
	},
	{
		0,1,1,1,0,
		0,1,0,1,0,
		0,1,1,1,0,
		0,1,0,1,0,
		0,1,1,1,0
	},
	{
		0,1,1,1,0,
		0,1,0,1,0,
		0,1,1,1,0,
		0,0,0,1,0,
		0,1,1,1,0
	}
					};